### ISSUE TITLE
phook on Homebrew

### ISSUE THREAD

**Issue by TheFox** [drinchev/phook#2]
phook is helpful to me. Especially for the [SSH and terminal background](http://www.drinchev.com/blog/ssh-and-terminal-background/) trick.

I would love to see phook as a [Homebrew](https://brew.sh/) package.

While Homebrew requires some project [popularity](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md) I added phook to [my Homebrew tap](https://github.com/TheFox/homebrew-brewery/blob/590282db6b8d391fe8b8c1097501943024d54c64/phook.rb):

```bash
brew tap thefox/brewery
brew install phook
```

This will install phook from [source](https://github.com/drinchev/phook/releases/tag/v0.0.4).

**Comment by drinchev** [comment]
That's great. I can add your public tap url to the readme, if you don't mind.

**Comment by TheFox** [comment]
Yeah sure, that would be great.

**Comment by drinchev** [comment]
I added your tap to the readme, but it seems that it is stuck to `0.0.3`.

Can you update it to the latest `0.0.5` ? :)

```
λ ~ ◆ brew install phook
==> Using the sandbox
==> Downloading https://github.com/drinchev/phook/archive/v0.0.3.tar.gz
Already downloaded: /Users/drinchev/Library/Caches/Homebrew/phook-0.0.3.tar.gz
```

Thanks, for your contribution.

**Comment by TheFox** [comment]
I don't know why it's using `0.0.3` when you install it. As you can see in commit [590282d](https://github.com/TheFox/homebrew-brewery/blob/590282db6b8d391fe8b8c1097501943024d54c64/phook.rb) it should be version `0.0.4`.

However, I updated it now to `0.0.5`. ✅ 
I'm now watching this repo, and I hope I get a notification when a new release is available. :)

**Comment by drinchev** [comment]
Checked it. Works properly 🎉  I guess I had some problems at my home Mac.

Closing this as resolved!

Thanks a lot!
