### ISSUE TITLE
Fails to install on Ubuntu

### ISSUE THREAD

**Issue by OmeGak** [drinchev/phook#5]
Fails to install on a clean Ubuntu 16.04.

```console
$ make install
gcc -o phook phook.c
phook.c:12:23: fatal error: sys/event.h: No such file or directory
compilation terminated.
Makefile:4: recipe for target 'phook' failed
make: *** [phook] Error 1
```

**Comment by drinchev** [comment]
Hey there.

As stated in the Readme ( https://github.com/drinchev/phook#installation ) The program is not ported to work on Linux. 

It uses internal macOS libs and it will be beyond my knowledge to make it work under Ubuntu.

I will close this, since there is no plan to develop that.

**Comment by OmeGak** [comment]
Missed that part, sorry!
