### ISSUE TITLE
Sierra 10.12.5 breaks phook?

### ISSUE THREAD

**Issue by TheLinuxNinja** [drinchev/phook#6]
I was using phook with iTerm2 according to the article written at http://www.drinchev.com/blog/ssh-and-terminal-background/ to set the iTerm2 Profile when ssh'ing into a remote machine.

Since today's MacOS update, when phook executes, it exits immediately without firing the command specified with the '-a' option instead of waiting for the ssh session to end.

An example of usage in ~/.ssh/config is:

Host test
Hostname 192.168.1.2
PermitLocalCommand yes
LocalCommand phook -e 'echo "\033]50;SetProfile=RedProfile\a"' -a 'echo "\033]50;SetProfile=Default\a"'
User testuser

Normally, this would switch iTerm2 to the Profile 'RedProfile' while connected to the 'test' system via ssh, then when ssh exits, the iTerm2 Profile would change to the 'Default' profile. Now, the profile does successfully switch to the Profile 'RedProfile', but does NOT switch back to the 'Default' profile when ssh exits, and I do not see a running 'phook' process while ssh session is running.

Is it likely something in MacOS has broken phook?

**Comment by drinchev** [comment]
I will have to update to 12.5 and tell you. Meanwhile can you run the example file from this repo and paste the output here 

```
$ cd examples
$ ./shell.sh
```

**Comment by drinchev** [comment]
It seems that it's working on 10.12.5.

Can you investigate more if it's from somewhere else?

![video-2](https://cloud.githubusercontent.com/assets/202919/26158469/42cae270-3b1c-11e7-95ec-336535f8bb09.gif)

**Comment by TheLinuxNinja** [comment]
ok, problem is elsewhere. I've tested this manually and it does appear to be working properly, but something somewhere else has broken. I'll track it down.

Thanks!
