### ISSUE TITLE
OSX Monterrey - after hooks not firing

### ISSUE THREAD

**Issue by martinlau** [drinchev/phook#8]
The standard shell.sh fails on Monterrey, the code:
```
if (ppid == 0)
    ppid = getppid();
```
isn't called. 

This is due to `ppid` being initialised to something non-zero in:

```
pid_t ppid, fpid;
```

I'm not too sure what the value is, they're values like: 217858064, 223969296, etc.

Fortunately the fix is quite simple: 

```
pid_t ppid = 0, fpid;
```

**Comment by drinchev** [comment]
I will make a release sometime tomorrow, @martinlau. Thanks for your contribution.
